// Products
export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const ADD_PRODUCTS = "ADD_PRODUCTS";
export const UPDATE_PRODUCTS = "UPDATE_PRODUCTS";
export const DELETE_PRODUCTS = "DELETE_PRODUCTS";
export const EDIT_PRODUCT = "EDIT_PRODUCT";
export const SEARCH_PRODUCT = "SEARCH_PRODUCT";
export const PRODUCT_SALE = "PRODUCT_SALE";
export const PRODUCT_FEATURED = "PRODUCT_FEATURED";
export const FILTER_TABLE_PRODUCT = "FILTER_TABLE_PRODUCT";
// Administration
export const CHECK_LOGIN_ADMIN = "CHECK_LOGIN_ADMIN";
export const FETCH_ADMIN_PROFILE = "FETCH_ADMIN_PROFILE";
export const UPDATE_INFO_ADMINISTRATION = "UPDATE_INFO_ADMINISTRATION";
// User
export const REGISTER_USER = "REGISTER_USER";
export const LOGIN_USER = "LOGIN_USER";
export const ADD_TO_CART = "ADD_TO_CART";
export const CHANGE_MESSAGE = "CHANGE_MESSAGE";
export const DELETE_PRODUCT_IN_CART = "DELETE_PRODUCT_IN_CART";
export const UPDATE_PRODUCT_IN_CART = "UPDATE_PRODUCT_IN_CART";
export const FETCH_ALL_CUSTOMER = "FETCH_ALL_CUSTOMER";
export const FETCH_CUSTOMER = "FETCH_CUSTOMER";
export const UPDATE_INFO_CUSTOMER = "UPDATE_INFO_CUSTOMER";
// Category
export const FETCH_ALL_CATEGORY = "FETCH_ALL_CATEGORY";
export const CATALOG_ADD = "CATALOG_ADD";
export const CATALOG_EDIT = 'CATALOG_EDIT';
export const CATALOG_SAVE = 'CATALOG_SAVE';
export const CATALOG_DELETE = 'CATALOG_DELETE';
export const GET_PRODUCT_FOLLOW_CATEGORY = 'GET_PRODUCT_FOLLOW_CATEGORY';
// Size Category
export const FETCH_ALL_SIZE_CATEGORY = "FETCH_ALL_SIZE_CATEGORY";
export const CATALOG_ADD_SIZE = "CATALOG_ADD_SIZE";
export const CATALOG_EDIT_SIZE = 'CATALOG_EDIT_SIZE';
export const CATALOG_SAVE_SIZE = 'CATALOG_SAVE_SIZE';
export const CATALOG_DELETE_SIZE = 'CATALOG_DELETE_SIZE';
// Color Category
export const FETCH_ALL_CATEGORY_COLOR = "FETCH_ALL_CATEGORY_COLOR";
export const CATALOG_ADD_COLOR = "CATALOG_ADD_COLOR";
export const CATALOG_EDIT_COLOR = 'CATALOG_EDIT_COLOR';
export const CATALOG_SAVE_COLOR = 'CATALOG_SAVE_COLOR';
export const CATALOG_DELETE_COLOR = 'CATALOG_DELETE_COLOR';
// Checkout 
export const ADD_ORDER = "ADD_ORDER";
export const ADD_ORDER_DETAIL = "ADD_ORDER_DETAIL";
// Order table admin
export const FETCH_ALL_ORDER = "FETCH_ALL_ORDER";
